apiVersion: v1
data:
  ### Aqua enforcer token input needed - Base64 encoded ###
  token: "YWI5M2I2OGItY2FiOC00NTk1LWJhMDUtMTg4N2ExYzg1NjE2"
kind: Secret
metadata:
  annotations:
    description: Aqua Enforcer token secret
  labels:
    deployedby: aqua-yaml
  name: enforcer-token
  namespace: aqua
type: Opaque
